In [1]:
import numpy as np

In [2]:
np.array(3)

array(3)

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [199]:
n = np.array([[1,2], [1.2, 1.3]])
type(n)
n

array([[1. , 2. ],
       [1.2, 1.3]])

In [203]:
n[:, 0]

array([1. , 1.2])

In [15]:
np.array([1, 2])
type(np)

module

In [20]:
np.linspace(1, 10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [42]:
np.random.randint(10)

5

In [51]:
np.random.random()*100

79.31392359677831

In [52]:
np.random.randint(0, 100, size=(4,5))

array([[63, 30, 95, 69,  2],
       [55, 79, 22, 33, 44],
       [65, 97, 43, 24, 19],
       [ 9, 34,  4, 77, 97]])

In [53]:
np.random.randint(0, 10, size=(1,2,3,4,5))

array([[[[[6, 5, 7, 0, 9],
          [4, 3, 7, 3, 3],
          [2, 7, 9, 4, 4],
          [3, 0, 8, 7, 6]],

         [[8, 3, 1, 7, 3],
          [7, 5, 6, 2, 0],
          [4, 2, 4, 1, 4],
          [5, 0, 1, 4, 3]],

         [[0, 1, 5, 2, 5],
          [3, 1, 9, 1, 4],
          [5, 6, 6, 1, 4],
          [4, 3, 2, 0, 9]]],


        [[[3, 8, 0, 9, 2],
          [0, 6, 3, 7, 7],
          [4, 3, 0, 8, 8],
          [9, 5, 5, 2, 0]],

         [[5, 0, 8, 9, 8],
          [8, 5, 2, 5, 4],
          [9, 2, 3, 2, 1],
          [0, 0, 2, 3, 5]],

         [[2, 7, 6, 7, 4],
          [7, 8, 8, 8, 6],
          [2, 1, 3, 7, 1],
          [9, 2, 0, 6, 0]]]]])

In [54]:
np.random.random(size=(2,3))

array([[0.97422032, 0.46993188, 0.29102476],
       [0.03107856, 0.67026399, 0.52731507]])

In [65]:
arr = np.random.randint(1, 10, size=(2,3))
arr.shape
arr.size
arr.dtype

dtype('int64')

In [71]:
arr = np.array([1,2, 'a', 1.1])
arr.shape
arr.size
arr.dtype

dtype('float64')

In [81]:
arr=np.random.randint(1, 10, size=(4,5))
arr

array([[1, 9, 8, 8, 9],
       [9, 3, 7, 8, 3],
       [4, 3, 4, 4, 2],
       [2, 6, 1, 4, 7]])

In [85]:
arr[2,4]

2

In [86]:
arr.reshape(5,4)

array([[1, 9, 8, 8],
       [9, 9, 3, 7],
       [8, 3, 4, 3],
       [4, 4, 2, 2],
       [6, 1, 4, 7]])

In [105]:
arr.reshape(20,)

array([1, 9, 8, 8, 9, 9, 3, 7, 8, 3, 4, 3, 4, 4, 2, 2, 6, 1, 4, 7])

In [106]:
arr.reshape(4,5)

array([[1, 9, 8, 8, 9],
       [9, 3, 7, 8, 3],
       [4, 3, 4, 4, 2],
       [2, 6, 1, 4, 7]])

In [110]:
np.concatenate((arr, arr), axis=1)

array([[1, 9, 8, 8, 9, 1, 9, 8, 8, 9],
       [9, 3, 7, 8, 3, 9, 3, 7, 8, 3],
       [4, 3, 4, 4, 2, 4, 3, 4, 4, 2],
       [2, 6, 1, 4, 7, 2, 6, 1, 4, 7]])

In [151]:
arr.sum()
arr.sum(axis=0)

array([16, 21, 20, 24, 21])

In [119]:
np.power(arr, 2)

array([[ 1, 81, 64, 64, 81],
       [81,  9, 49, 64,  9],
       [16,  9, 16, 16,  4],
       [ 4, 36,  1, 16, 49]])

In [128]:
np.exp(1)
np.log(2)

0.6931471805599453

In [129]:
arr

array([[1, 9, 8, 8, 9],
       [9, 3, 7, 8, 3],
       [4, 3, 4, 4, 2],
       [2, 6, 1, 4, 7]])

In [130]:
np.argmax(arr)
np.argmin(arr)
np.median(arr) 

4.0

In [136]:
np.std(arr)

array([[1, 9, 8, 8, 9],
       [9, 3, 7, 8, 3],
       [4, 3, 4, 4, 2],
       [2, 6, 1, 4, 7]])

In [154]:
np.sort(arr, axis=0)

array([[1, 3, 1, 4, 2],
       [2, 3, 4, 4, 3],
       [4, 6, 7, 8, 7],
       [9, 9, 8, 8, 9]])

In [157]:
arr.mean()

5.1

In [159]:
import pandas as pd
from pandas import Series, DataFrame

In [166]:
Series(data=[1,2,'a'], index=['a', 'b', 'c'])

a    1
b    2
c    a
dtype: object

In [173]:
Series(data=np.random.randint(1, 100, size=(10)))

0    48
1    22
2    91
3    55
4    95
5    35
6    37
7    56
8    77
9    35
dtype: int64

In [183]:
s = Series(data=[1,1,2,3,4])

In [186]:
s.unique()

array([1, 2, 3, 4])

In [189]:
pd.isnull(s)
s.notnull()

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [193]:
s[[True, False, True, False, True]]

0    1
2    2
4    4
dtype: int64

In [217]:
s = Series([1,2,3,4], index=['a', 'b', 'c', 'd'])
s

a    1
b    2
c    3
d    4
dtype: int64

In [215]:
s['a':'c']
s[0:2]
s.shape
s.index
s.size
s.dtype
s.values
s.head(2)
s.tail(2)

c    3
d    4
dtype: int64

In [230]:
s2 = Series([1,2,3,4], index=['a', 'b', 3, 4])
s2
s.add(s2, fill_value=2)

3    5.0
4    6.0
a    2.0
b    4.0
c    5.0
d    6.0
dtype: float64

## dataframe

In [248]:
df = DataFrame(data=np.random.randint(1,10, size=(2,3)), index=('a', 'b'), columns=('A', 'B', 'C'))
df

A  B  C
a  1  7  4
b  7  6  6

In [234]:
dic = {
    '张三':[11,22,33,44],
    '李四':[55,66,77,88]
}
df_score = DataFrame(data=dic,index=['语文','数学','英语','理综'])
df_score

张三  李四
语文  11  55
数学  22  66
英语  33  77
理综  44  88

In [241]:
df.shape
df.size
df.index
df.values
df.columns

Index(['1', '2', '3'], dtype='object')

In [251]:
df

A  B  C
a  1  7  4
b  7  6  6

In [252]:
df.A

a    1
b    7
Name: A, dtype: int64

In [257]:
df['A']
df[['A', 'B']]

A  B
a  1  7
b  7  6

In [269]:
df.iloc[[0,]]

A  B  C
a  1  7  4

In [268]:
df.loc[['a',]]

A  B  C
a  1  7  4

In [273]:
df[:'a']

A  B  C
a  1  7  4

In [275]:
df[0:1]

A  B  C
a  1  7  4

In [278]:
df.iloc[:, 0:1]
df.loc[:, 'A':'B']

A  B
a  1  7
b  7  6

In [289]:
df

A  B  C
a  1  7  4
b  7  6  6

In [291]:
df2 = DataFrame(data=np.random.randint(1,10, size=(2, 3)), index=('a', 'b'), columns=('A', 'B', 3))
df2

A  B  3
a  8  4  5
b  5  3  3

In [298]:
pd.concat((df, df2), axis=0, join='outer', sort=True)

A  B    C    3
a  1  7  4.0  NaN
b  7  6  6.0  NaN
a  8  4  NaN  5.0
b  5  3  NaN  3.0

In [310]:
dic1 = {
    'name':['henry','echo', 'dean', 'tom'],
    'apartment':['tech','sale','hr', 'xx'],
}
dic2 = {
    'apart':['tech','sale','hr', 'acctounting'],
    'supervisor':['diane', 'oleg', 'iris', 'elaine']
}

df1 = DataFrame(dic1, index=['a', 'b', 'c', 'd'])
df2 = DataFrame(dic2, index=['a', 'b', 'c', 'd'])

In [311]:
df2

apart supervisor
a         tech      diane
b         sale       oleg
c           hr       iris
d  acctounting     elaine

In [313]:
pd.merge(left=df1, right=df2, left_on='apartment', right_on='apart', how='outer')

name apartment        apart supervisor
0  henry      tech         tech      diane
1   echo      sale         sale       oleg
2   dean        hr           hr       iris
3    tom        xx          NaN        NaN
4    NaN       NaN  acctounting     elaine

In [330]:
dic = {
    'name':['周杰伦','张三','周杰伦'],
    'salary':[15000,20000,15000]
}
df = DataFrame(data=dic)
df

name  salary
0  周杰伦   15000
1   张三   20000
2  周杰伦   15000

In [331]:
dic = {
    '周杰伦':'jay',
    '张三':'tom'
}
df['ename'] = df.name.map(dic)
df

name  salary ename
0  周杰伦   15000   jay
1   张三   20000   tom
2  周杰伦   15000   jay

In [332]:
np.random.permutation(5)

array([4, 0, 3, 1, 2])

In [336]:
df = DataFrame(np.random.random(size=(1000, 3)), columns=['A', 'B', 'C'])
df

A         B         C
0    0.237567  0.944420  0.047556
1    0.086638  0.185784  0.799302
2    0.770420  0.928712  0.932285
3    0.909925  0.146701  0.853985
4    0.211621  0.647272  0.946829
..        ...       ...       ...
995  0.718396  0.759049  0.449614
996  0.703445  0.205175  0.244154
997  0.638193  0.870992  0.608616
998  0.821021  0.014109  0.705126
999  0.222248  0.904606  0.732148

[1000 rows x 3 columns]

In [344]:
df.take(indices=np.random.permutation(1000), axis=0).take(indices=np.random.permutation(3), axis=1)

C         A         B
439  0.840888  0.058957  0.310654
635  0.051856  0.851384  0.822938
820  0.257648  0.637818  0.269564
395  0.711145  0.652352  0.722438
40   0.141140  0.198417  0.411474
..        ...       ...       ...
714  0.436014  0.271474  0.949461
528  0.970163  0.132550  0.948313
511  0.965548  0.306646  0.043422
63   0.757830  0.230770  0.673480
704  0.825967  0.523127  0.175704

[1000 rows x 3 columns]

In [345]:
df = DataFrame({'item':['Apple','Banana','Orange','Banana','Orange','Apple'],
                'price':[4,3,3,2.5,4,2],
               'color':['red','yellow','yellow','green','green','green'],
               'weight':[12,20,50,30,20,44]})
df

item  price   color  weight
0   Apple    4.0     red      12
1  Banana    3.0  yellow      20
2  Orange    3.0  yellow      50
3  Banana    2.5   green      30
4  Orange    4.0   green      20
5   Apple    2.0   green      44

In [366]:
df.groupby(by='item', axis=0).price.std()

item
Apple     1.414214
Banana    0.353553
Orange    0.707107
Name: price, dtype: float64

In [367]:
def my_mean(p):
    sum = 0
    for i in p:
        sum += i
    return sum/len(p)

In [375]:
aplly_my_mean = df.groupby(by='item', axis=0).price.apply(my_mean)
df['apply_my_mean'] = df.item.map(aplly_my_mean)
df

item  price   color  weight  apply_my_mean  transform_my_mean
0   Apple    4.0     red      12           3.00               3.00
1  Banana    3.0  yellow      20           2.75               2.75
2  Orange    3.0  yellow      50           3.50               3.50
3  Banana    2.5   green      30           2.75               2.75
4  Orange    4.0   green      20           3.50               3.50
5   Apple    2.0   green      44           3.00               3.00

In [376]:
df['transform_my_mean'] = df.groupby(by='item', axis=0).price.transform(my_mean)
df

item  price   color  weight  apply_my_mean  transform_my_mean
0   Apple    4.0     red      12           3.00               3.00
1  Banana    3.0  yellow      20           2.75               2.75
2  Orange    3.0  yellow      50           3.50               3.50
3  Banana    2.5   green      30           2.75               2.75
4  Orange    4.0   green      20           3.50               3.50
5   Apple    2.0   green      44           3.00               3.00